config/routes.rb
Rails.application.routes.draw do

  devise_for :admins

  ##############################################################################
  # Admins
  namespace :admins do
    get '/',        to: 'dashboard#index'
    resources :products
    resources :car_models
    resources :contacts
    resources :posts
  end

  resources :car_models, only: [:show] do
    get '/:slug', on: :collection, to: 'car_models#show'
  end

  resources :products, only: [:show, :index] do
    get '/:slug', on: :collection, to: 'products#show'
  end

  resources :contacts, only: [:index, :create]

  get 'tin-tuc/:slug', to: 'posts#show', as: :post
  get 'tin-tuc', to: 'posts#index', as: :posts

  get 'introduces/about_us', to: 'introduce#about_us'
  get 'introduces/super_handsome_developer', to: 'introduce#developer', as: :introduces_developer

  root 'home#index'
end

app/models/car_model.rb
class CarModel < ApplicationRecord
  has_one_attached :image
  has_many :products

end

app/controllers/admins/car_models_controller.rb
class Admins::CarModelsController < Admins::AdminsController
  before_action :set_admins_car_model, only: [:show, :edit, :update, :destroy]

  def index
    @admins_car_models = CarModel.all
  end

  def show
  end

  def new
    @admins_car_model = CarModel.new
  end

  def create
    @admins_car_model = CarModel.new(admins_car_model_params)

    respond_to do |format|
      if @admins_car_model.save
        format.html { redirect_to admins_car_model_path(@admins_car_model), notice: 'Car model was successfully created.' }
        format.json { render action: 'show', status: :created, location: @admins_car_model }
      else
        format.html { render action: 'new' }
        format.json { render json: @admins_car_model.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    if @admins_car_model.update(admins_car_model_params)
      redirect_to admins_car_model_path(@admins_car_model), notice: 'Car model was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @admins_car_model.destroy
    respond_to do |format|
      format.html { redirect_to admins_car_models_path, notice: 'Car model was successfully deleted.' }
    end
  end

  private

  def admins_car_model_params
    params.require(:car_model).permit!
  end

  def set_admins_car_model
    @admins_car_model = CarModel.find(params[:id])
  end

end

app/controllers/car_models_controller.rb
class CarModelsController < ApplicationController

  def show
    @car_model = CarModel.includes(:products).find_by_slug(params[:slug])
  end

  private

  def car_model_params
    params.require(:car_model).permit(:name, :image)
  end
end

app/views/admins/car_models/_form.html.haml
= simple_form_for @admins_car_model, url: url do |f|
  .row
    .col-md-6
      .row
        .col-md-6
          .form-group
            = f.input :name, label: 'Tên', input_html: { class: 'form-control'}
        .col-md-6
          .form-group
            = f.input :lowest_price, label: 'Giá chỉ từ', as: :numeric, input_html: { class: 'form-control'}
        .col-md-12
          .form-group
            = f.input :slug, label: 'Đường dẫn', input_html: { class: 'form-control'}
    .col-md-6
      .row
        .col-md-6
          .form-group
            .image-border
              .image-border-content
                .parent
                  .image-content.image-media-preview
                    - if f.object.image.present?
                      = image_tag( url_for(f.object.image), class: "img-fluid", width: 200)
                    - else
                      .font-awesome-image
                        %i.far.fa-image
                %label.btn.btn-light.btn-sm{:style => "width: 100%;"}
                  Add a image!
                  %span{:style => "display:none;"}
                    = f.input :image, label: 'Hình ảnh', as: :file, input_html: { class:"attach_image"}
    .clearfix

    .col-xs-12
      = f.submit "Lưu lại", class: "btn btn-primary"

app/views/admins/car_models/edit.html.haml
.container
	%p
		= link_to 'Quay lại', admins_car_models_path
	%h1 Sửa mẫu xe
	= render 'form', url: admins_car_model_path(@admins_car_model)

app/views/admins/car_models/index.html.haml
.container
  - flash.each do |key, value|
    .alert.alert-warning.alert-dismissible.fade.show{:role => "alert"}
      %strong= value
      %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
        %span{"aria-hidden" => "true"} ×
  .row
    .col-xs-12
      = link_to 'Tạo mẫu xe mới', new_admins_car_model_path, class: 'btn btn-success btn-sm'
      %h1 Tất cả mẫu xe
      .table-responsive
        %table.table.table-bordered
          %thead
            %tr
              %th ID
              %th Tên
              %th Đường dẫn
              %th Giá chỉ từ
              %th Hình mẫu
              %th
              %th
              %th
          %tbody
            - @admins_car_models.each do |car_model|
              %tr
                %td= car_model.id
                %td= car_model.name
                %td= car_model.slug
                %td= "#{number_to_currency(car_model.lowest_price, precision: 0, unit: '')} VND"
                %td
                  - if car_model.image.present?
                    = image_tag(car_model.image&.blob&.service_url, class: "img-fluid", width: 200)
                %td= link_to 'Xem', admins_car_model_path(car_model)
                %td= link_to 'Sửa' , edit_admins_car_model_path(car_model)
                %td= link_to 'Xoá', admins_car_model_path(car_model) , method: :delete, data: { confirm: 'Are you sure, you want to delete this Car model?' }

app/views/admins/car_models/new.html.haml
.container
  %p
    = link_to 'Quay lại', admins_car_models_path
  %h1 Mẫu xe mới
  = render 'form', url: admins_car_models_path

app/views/admins/car_models/show.html.haml
.container
  - flash.each do |key, value|
    .alert.alert-warning.alert-dismissible.fade.show{:role => "alert"}
      %strong= value
      %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
        %span{"aria-hidden" => "true"} ×
  %p
    = link_to 'Quay lại', admins_car_models_path
    |
    = link_to 'Sửa', edit_admins_car_model_path

    .row
      .table-responsive
        %table.table.table-bordered
          %tr
            %th ID
            %td= @admins_car_model.id
          %tr
            %th Tên
            %td= @admins_car_model.name
          %tr
            %th Đường dẫn
            %td= @admins_car_model.slug
          %tr
            %th Giá chỉ từ
            %td="#{number_to_currency(@admins_car_model.lowest_price, precision: 0, unit: '')} VND"
          %tr
            %th Hình ảnh
            %td
              - if @admins_car_model.image.present?
                = image_tag(@admins_car_model.image&.blob&.service_url, class: "img-fluid", width: 200)