config/routes.rb
Rails.application.routes.draw do

  devise_for :admins

  ##############################################################################
  # Admins
  namespace :admins do
    get '/',        to: 'dashboard#index'
    resources :products
    resources :car_models
    resources :contacts
    resources :posts
  end

  resources :car_models, only: [:show] do
    get '/:slug', on: :collection, to: 'car_models#show'
  end

  resources :products, only: [:show, :index] do
    get '/:slug', on: :collection, to: 'products#show'
  end

  resources :contacts, only: [:index, :create]

  get 'tin-tuc/:slug', to: 'posts#show', as: :post
  get 'tin-tuc', to: 'posts#index', as: :posts

  get 'introduces/about_us', to: 'introduce#about_us'
  get 'introduces/super_handsome_developer', to: 'introduce#developer', as: :introduces_developer

  root 'home#index'
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :background
end

app/controllers/admins/posts_controller.rb
class Admins::PostsController < Admins::AdminsController
	before_action :set_admins_post, only: [:show, :edit, :update, :destroy]

  def index
    @admins_posts = Post.all
  end

	def new
    @admins_post = Post.new
  end

	def create
    @admins_post = Post.new(admins_post_params)

    respond_to do |format|
      if @admins_post.save
        format.html { redirect_to admins_post_path(@admins_post), notice: 'Bài đăng đã được tạo thành công' }
        format.json { render action: 'show', status: :created, location: @admins_post }
      else
        format.html { render action: 'new' }
        format.json { render json: @admins_post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    if @admins_post.update(admins_post_params)
      redirect_to admins_post_path(@admins_post), notice: 'Bài viết đã được cập nhật thành công.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @admins_post.destroy
    respond_to do |format|
      format.html { redirect_to admins_posts_path, notice: 'Bài viết đã được xoá thành công.' }
    end
  end

	private

	def set_admins_post
    @admins_post = Post.find_by(id: params[:id])
  end

	def admins_post_params
    params.require(:post).permit!
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find_by_slug(params[:slug])
  end
end

app/views/admins/posts/_form.html.haml
= simple_form_for @admins_post, url: url do |f|
  .row
    .col-md-4
      .form-group
        = f.input :title, label: 'Tiêu đề', input_html: { class: 'form-control'}
    .col-md-4
      .form-group
        = f.input :slug, label: 'slug', input_html: { class: 'form-control'}
    .col-md-4
      .form-group
        .image-border
          .image-border-content
            .parent
              .image-content.image-media-preview
                - if f.object.background.present?
                  = image_tag( url_for(f.object.background), class: "img-fluid", width: 200)
                - else
                  .font-awesome-image
                    %i.far.fa-image
            %label.btn.btn-light.btn-sm{:style => "width: 100%;"}
              Add a image!
              %span{:style => "display:none;"}
                = f.input :background, label: 'Background', as: :file, input_html: { class:"attach_image"}
    .col-md-12
      .form-group
        = f.input :body, label: 'Nội dung', as: :text, input_html: { class: 'form-control', rows: 10}
    .clearfix
    .col-xs-12
      .form-group
      = f.submit "Lưu lại", class: "btn btn-primary"

app/views/admins/posts/edit.html.haml
.container
	%p
		= link_to 'Quay lại', admins_posts_path
	%h1 Sửa bài viết
	= render 'form', url: admins_post_path(@admins_post)

app/views/admins/posts/index.html.haml
.container
  - flash.each do |key, value|
    .alert.alert-warning.alert-dismissible.fade.show{:role => "alert"}
      %strong= value
      %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
        %span{"aria-hidden" => "true"} ×
  .row
    .col-xs-12
      = link_to 'Tạo bài viết mới', new_admins_post_path, class: 'btn btn-success btn-sm'
      %h1 Tất cả bài viết
      .table-responsive
        %table.table.table-bordered
          %thead
            %tr
              %th STT
              %th Tiêu đề
              %th Slug
              %th Background
              %th
              %th
              %th
              %th
          %tbody
            - @admins_posts.each_with_index do |post, index|
              %tr
                %td= index + 1
                %td= post.title
                %td= post.slug
                %td
                  - if post.background.present?
                    = image_tag( url_for(post.background), class: "img-fluid", width: 200 )
                %td= link_to 'Preview', post_path(post.slug), target: :_blank
                %td= link_to 'Xem', admins_post_path(post)
                %td= link_to 'Sửa' , edit_admins_post_path(post)
                %td= link_to 'Xoá', admins_post_path(post) , method: :delete, data: { confirm: "Bạn có chắc, bạn muốn xoá bài viết này?" }

app/views/admins/posts/new.html.haml
.container
  %p
    = link_to 'Quay lại', admins_posts_path
  %h1 Bài viết mới
  = render 'form', url: admins_posts_path

app/views/admins/posts/show.html.haml
.container
  - flash.each do |key, value|
    .alert.alert-warning.alert-dismissible.fade.show{:role => "alert"}
      %strong= value
      %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
        %span{"aria-hidden" => "true"} ×
  %p
    = link_to 'Quay lại', admins_posts_path
    |
    = link_to 'Sửa', edit_admins_post_path
    .row
      .table-responsive
        %table.table.table-bordered
          %tr
            %th ID
            %td= @admins_post.id
          %tr
            %th Tiêu đề
            %td= @admins_post.title
          %tr
            %th slug
            %td= @admins_post.slug
          %tr
            %th Background
            %td
              - if @admins_post.background.present?
                = image_tag( url_for(@admins_post.background), class: "img-fluid", width: 200)
          %tr
            %th Nội dung
            %td= simple_format @admins_post.body