config/routes.rb
Rails.application.routes.draw do

  devise_for :admins

  ##############################################################################
  # Admins
  namespace :admins do
    get '/',        to: 'dashboard#index'
    resources :products
    resources :car_models
    resources :contacts
    resources :posts
  end

  resources :car_models, only: [:show] do
    get '/:slug', on: :collection, to: 'car_models#show'
  end

  resources :products, only: [:show, :index] do
    get '/:slug', on: :collection, to: 'products#show'
  end

  resources :contacts, only: [:index, :create]

  get 'tin-tuc/:slug', to: 'posts#show', as: :post
  get 'tin-tuc', to: 'posts#index', as: :posts

  get 'introduces/about_us', to: 'introduce#about_us'
  get 'introduces/super_handsome_developer', to: 'introduce#developer', as: :introduces_developer

  root 'home#index'
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, :phone_number, :message, presence: true
  validates :phone_number, numericality: true,
                          length: {minimum: 10, maximum: 15}
end

app/controllers/admins/contacts_controller.rb
class Admins::ContactsController < Admins::AdminsController

  def index
    @admins_conacts = Contact.all
  end

  def show
    @admins_conact = Contact.find(params[:id])
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def index
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        ContactMailer.with(contact: @contact).notification.deliver_now
        format.html {redirect_to contacts_path}
        flash[:success] = true
        format.js {}
      else
        format.html {render :index}
        format.json {render json: @contact.errors, status: :unprocessable_entity}
        format.js   {}

        @error_name = []
        @error_phone = []
        @error_message = []

        @error_name.push(@contact.errors["name"][0]) if (@contact.errors["name"] != nil)
        @error_phone.push(@contact.errors["phone_number"][0]) if (@contact.errors["phone_number"] != nil)
        @error_message.push(@contact.errors["message"][0]) if (@contact.errors["message"] != nil)
      end
    end
  end

  private ##

  def contact_params
    params.require(:contact).permit(:name, :phone_number, :message, :email, :product)
  end
end

app/views/admins/contacts/index.html.haml
.container
  .row
    .col-xs-12
      %h1 Tất cả liên hệ
      .table-responsive
        %table.table.table-bordered
          %thead
            %tr
              %th ID
              %th Tên khách hàng
              %th Số điện thoại
              %th Emmail
              %th Xe cần tư vấn
              %th Tin nhắn
              %th
          %tbody
            - @admins_conacts.each do |contact|
              %tr
                %td= contact.id
                %td= contact.name
                %td= contact.phone_number
                %td= contact.email
                %td= contact.product
                %td= contact.message.truncate_words(10)
                %td= link_to 'Xem chi tiết', admins_contact_path(contact)

app/views/admins/contacts/show.html.haml
.container
  %p
    = link_to 'Quay lại', admins_contacts_path

    .row
      .table-responsive
        %table.table.table-bordered
          %tr
            %th ID
            %td= @admins_conact.id
          %tr
            %th Tên khách hàng
            %td= @admins_conact.name
          %tr
            %th Số điện thoại
            %td= @admins_conact.phone_number
          %tr
            %th Email
            %td= @admins_conact.email
          %tr
            %th Xe cần tư vấn
            %td= @admins_conact.product
          %tr
            %th Tin nhắn
            %td= simple_format(@admins_conact.message)